# @format

name: Sync Repos

on:
  push:
    branches:
      - main
  # You can add more triggers, such as scheduled events
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Push to destination repository
        run: |
          git config --global user.email github-actions@acceltra.cloud
          git config --global user.name "AcceltraGithubActions"
          rm -rf acceltra-website2
          git clone https://${{ env.ORG_NAME }}:${{ secrets.PAT }}@github.com/${{ env.ORG_NAME }}/acceltra-website2.git
          
          rsync -a --delete --exclude='.git' --exclude='.github' --exclude='acceltra-website2' "$GITHUB_WORKSPACE/" .
          cd acceltra-website2
          
          git add -A
          git commit -m "Force sync from ${ORIGINAL_REPO_NAME} (exclude .github)" || true
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
          ORG_NAME: saad-acc
