# @format

name: Sync Repos

on:
  push:
    branches:
      - main
  # You can add more triggers, such as scheduled events
  # schedule:
  #   - cron: '0 0 * * *'

permissions:
  contents: read
  
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Push to destination repository
        shell: bash
        run: |
          git config --global user.email github-actions@acceltra.cloud
          git config --global user.name "AcceltraGithubActions"
          
          DEST_DIR="$(mktemp -d)"
          git clone "https://${ORG_NAME}:${PAT}@github.com/${ORG_NAME}/acceltra-website2.git" "$DEST_DIR"
          cd "$DEST_DIR"
          
          rsync -a --delete --exclude='.git' --exclude='.github' "$GITHUB_WORKSPACE/" .
          git add -A
          git commit -m "Force sync from ${ORIGINAL_REPO_NAME} (exclude .github)" || true
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
          ORG_NAME: saad-acc
